name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
  SERVER_SSH: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.7.0

    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Gradle Build Action
      uses: gradle/gradle-build-action@v2.4.0
      
    - name: Build server
      run: gradle build

    - name: Setup SSH
      uses: kielabokkie/ssh-key-and-known-hosts-action@v1.3.5
      with:
        ssh-private-key: ${{ env.SERVER_SSH }}
        ssh-host: ${{ env.SERVER_HOST }}

    - name: web deploy anything
      uses: SamKirkland/web-deploy@v1
      with:
         target-server: ${{ env.SERVER_HOST }}
         private-ssh-key: ${{ env.SERVER_SSH }}
         remote-user: ${{ env.SERVER_USER }}
         source-path: build/distributions/
         destination-path: /home/github_action/ktor/
