name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Gradle Build Action
      uses: gradle/gradle-build-action@v2.4.0

    - name: Build server
      run: gradle build

    - name: FTP/SFTP file deployer
      uses: milanmk/actions-file-deployer@1.12
      with:
        remote-host: ${{ env.SERVER_HOST }}
        remote-user: ${{ env.SERVER_USER }}
        remote-password: ${{ env.SERVER_PASSWORD }}
        proxy: false
        remote-path: /home/github_action/ktor/
        local-path: build/distributions/
