name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
  SERVER_SSH: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.7.0
      with:
        fetch-depth: 0

    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Gradle Build Action
      uses: gradle/gradle-build-action@v2.4.0

    - name: Build server
      run: gradle build
      
    - name: Setup SSH Keys and known_hosts
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ env.SERVER_SSH }}"

    - name: Some task that fetches dependencies
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: ./fetch-deps.sh
      
    - name: Deploy with rsync
      run: rsync -avz -e "ssh -p ${{ secrets.SERVER_SSH_PORT }}" build/distributions/ ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:/home/github_action/ktor/
