name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Gradle Build Action
      uses: gradle/gradle-build-action@v2.4.0

    - name: Build server
      run: ./gradlew build

    - name: Deploy server
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        server: ${{ env.SERVER_HOST }}
        username: ${{ env.SERVER_USER }}
        password: ${{ env.SERVER_PASSWORD }}
        server-dir: /ktor/ktorserver/
        local-dir: build/distributions/
        args: --parallel=10
