name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
  SERVER_SSH: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.7.0
      with:
        fetch-depth: 0

    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Gradle Build Action
      uses: gradle/gradle-build-action@v2.4.0

    - name: Build server
      run: gradle build
      
    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ env.SERVER_USER }}
        password: ${{ env.SERVER_PASSWORD }}
        server: ${{ env.SERVER_HOST }}
        ssh_private_key: ${{ env.SERVER_SSH }}
        local_path: build/distributions/
        remote_path: /home/github_action/ktor/
